///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace RxWebPageNavigation
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the RxWebPageNavigationRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
    [RepositoryFolder("75063776-e4fe-45e0-8946-473f473d6841")]
    public partial class RxWebPageNavigationRepository : RepoGenBaseFolder
    {
        static RxWebPageNavigationRepository instance = new RxWebPageNavigationRepository();
        RxWebPageNavigationRepositoryFolders.BBCHomeInternetExplorerAppFolder _bbchomeinternetexplorer;
        RxWebPageNavigationRepositoryFolders.BBCHomeAppFolder _bbchome;

        /// <summary>
        /// Gets the singleton class instance representing the RxWebPageNavigationRepository element repository.
        /// </summary>
        [RepositoryFolder("75063776-e4fe-45e0-8946-473f473d6841")]
        public static RxWebPageNavigationRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public RxWebPageNavigationRepository() 
            : base("RxWebPageNavigationRepository", "/", null, 0, false, "75063776-e4fe-45e0-8946-473f473d6841", ".\\RepositoryImages\\RxWebPageNavigationRepository75063776.rximgres")
        {
            _bbchomeinternetexplorer = new RxWebPageNavigationRepositoryFolders.BBCHomeInternetExplorerAppFolder(this);
            _bbchome = new RxWebPageNavigationRepositoryFolders.BBCHomeAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("75063776-e4fe-45e0-8946-473f473d6841")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The BBCHomeInternetExplorer folder.
        /// </summary>
        [RepositoryFolder("a85885b4-a7e6-4247-a81d-abb9e4da48ec")]
        public virtual RxWebPageNavigationRepositoryFolders.BBCHomeInternetExplorerAppFolder BBCHomeInternetExplorer
        {
            get { return _bbchomeinternetexplorer; }
        }

        /// <summary>
        /// The BBCHome folder.
        /// </summary>
        [RepositoryFolder("4d0aa9de-0098-45f5-acc7-5ce0ef1a8ace")]
        public virtual RxWebPageNavigationRepositoryFolders.BBCHomeAppFolder BBCHome
        {
            get { return _bbchome; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
    public partial class RxWebPageNavigationRepositoryFolders
    {
        /// <summary>
        /// The BBCHomeInternetExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("a85885b4-a7e6-4247-a81d-abb9e4da48ec")]
        public partial class BBCHomeInternetExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _askmelaterInfo;
            RepoItemInfo _clientcaptionInfo;

            /// <summary>
            /// Creates a new BBCHomeInternetExplorer  folder.
            /// </summary>
            public BBCHomeInternetExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("BBCHomeInternetExplorer", "/form[@title~'^BBC\\ -\\ Home\\ -\\ Internet\\ Exp']", parentFolder, 30000, null, true, "a85885b4-a7e6-4247-a81d-abb9e4da48ec", "")
            {
                _askmelaterInfo = new RepoItemInfo(this, "AskMeLater", ".//toolbar[@accessiblename='Notification']/button[@accessiblename='Ask me later']", 30000, null, "db5e4116-3a6c-46b0-bb37-d078d29f4cfd");
                _clientcaptionInfo = new RepoItemInfo(this, "ClientCaption", "element[@class='Client Caption']", 30000, null, "a8f3d062-21df-41e7-80d9-4447537f1f0a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a85885b4-a7e6-4247-a81d-abb9e4da48ec")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a85885b4-a7e6-4247-a81d-abb9e4da48ec")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AskMeLater item.
            /// </summary>
            [RepositoryItem("db5e4116-3a6c-46b0-bb37-d078d29f4cfd")]
            public virtual Ranorex.Button AskMeLater
            {
                get
                {
                    return _askmelaterInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The AskMeLater item info.
            /// </summary>
            [RepositoryItemInfo("db5e4116-3a6c-46b0-bb37-d078d29f4cfd")]
            public virtual RepoItemInfo AskMeLaterInfo
            {
                get
                {
                    return _askmelaterInfo;
                }
            }

            /// <summary>
            /// The ClientCaption item.
            /// </summary>
            [RepositoryItem("a8f3d062-21df-41e7-80d9-4447537f1f0a")]
            public virtual Ranorex.Unknown ClientCaption
            {
                get
                {
                    return _clientcaptionInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The ClientCaption item info.
            /// </summary>
            [RepositoryItemInfo("a8f3d062-21df-41e7-80d9-4447537f1f0a")]
            public virtual RepoItemInfo ClientCaptionInfo
            {
                get
                {
                    return _clientcaptionInfo;
                }
            }
        }

        /// <summary>
        /// The BBCHomeAppFolder folder.
        /// </summary>
        [RepositoryFolder("4d0aa9de-0098-45f5-acc7-5ce0ef1a8ace")]
        public partial class BBCHomeAppFolder : RepoGenBaseFolder
        {
            WelcomeToTheBBCInfoClass _welcometothebbcInfo;
            NewsInfoClass _newsInfo;
            HomepageInfoClass _homepageInfo;

            /// <summary>
            /// Creates a new BBCHome  folder.
            /// </summary>
            public BBCHomeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("BBCHome", "/dom[@domain='www.bbc.co.uk']", parentFolder, 30000, null, false, "4d0aa9de-0098-45f5-acc7-5ce0ef1a8ace", "")
            {
                _welcometothebbcInfo = new WelcomeToTheBBCInfoClass(this);
                _newsInfo = new NewsInfoClass(this);
                _homepageInfo = new HomepageInfoClass(this);
            }

            /// <summary>
            /// The WelcomeToTheBBCInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("f5fa665f-13b5-4732-912b-d882f65a38c5")]
            public class WelcomeToTheBBCInfoClass : RepoItemInfo
            {
                /// <summary>
                /// WelcomeToTheBBCInfoClass class constructor.
                /// </summary>
                public WelcomeToTheBBCInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "WelcomeToTheBBC", ".//div[#'orb-modules']/div[2]/section[1]/?/?/h2[@innertext='Welcome to the BBC']", 30000, null, "f5fa665f-13b5-4732-912b-d882f65a38c5")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("90ae7ae3-7e13-4d86-a9a0-895346f3ba4c")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("90ae7ae3-7e13-4d86-a9a0-895346f3ba4c");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("90ae7ae3-7e13-4d86-a9a0-895346f3ba4c")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("90ae7ae3-7e13-4d86-a9a0-895346f3ba4c", cropRect);
                }
            }

            /// <summary>
            /// The NewsInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("56fa801f-2603-486f-adab-5da1b8113bec")]
            public class NewsInfoClass : RepoItemInfo
            {
                /// <summary>
                /// NewsInfoClass class constructor.
                /// </summary>
                public NewsInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "News", ".//div[#'orb-nav-links']//a[@innertext='News']", 30000, null, "56fa801f-2603-486f-adab-5da1b8113bec")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("70628064-f9a1-4f82-b076-1c428cbe4f91")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("70628064-f9a1-4f82-b076-1c428cbe4f91");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("70628064-f9a1-4f82-b076-1c428cbe4f91")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("70628064-f9a1-4f82-b076-1c428cbe4f91", cropRect);
                }
            }

            /// <summary>
            /// The HomepageInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("e28361f0-555e-42ed-a7f5-2343884a426e")]
            public class HomepageInfoClass : RepoItemInfo
            {
                /// <summary>
                /// HomepageInfoClass class constructor.
                /// </summary>
                public HomepageInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "Homepage", ".//div[#'orb-header']//a[@innertext='Homepage']", 30000, null, "e28361f0-555e-42ed-a7f5-2343884a426e")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("17e7e994-3efb-4878-b43a-21c3f3151e9b")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("17e7e994-3efb-4878-b43a-21c3f3151e9b");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("17e7e994-3efb-4878-b43a-21c3f3151e9b")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("17e7e994-3efb-4878-b43a-21c3f3151e9b", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4d0aa9de-0098-45f5-acc7-5ce0ef1a8ace")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4d0aa9de-0098-45f5-acc7-5ce0ef1a8ace")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The WelcomeToTheBBC item.
            /// </summary>
            [RepositoryItem("f5fa665f-13b5-4732-912b-d882f65a38c5")]
            public virtual Ranorex.H2Tag WelcomeToTheBBC
            {
                get
                {
                    return _welcometothebbcInfo.CreateAdapter<Ranorex.H2Tag>(true);
                }
            }

            /// <summary>
            /// The WelcomeToTheBBC item info.
            /// </summary>
            [RepositoryItemInfo("f5fa665f-13b5-4732-912b-d882f65a38c5")]
            public virtual WelcomeToTheBBCInfoClass WelcomeToTheBBCInfo
            {
                get
                {
                    return _welcometothebbcInfo;
                }
            }

            /// <summary>
            /// The News item.
            /// </summary>
            [RepositoryItem("56fa801f-2603-486f-adab-5da1b8113bec")]
            public virtual Ranorex.ATag News
            {
                get
                {
                    return _newsInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The News item info.
            /// </summary>
            [RepositoryItemInfo("56fa801f-2603-486f-adab-5da1b8113bec")]
            public virtual NewsInfoClass NewsInfo
            {
                get
                {
                    return _newsInfo;
                }
            }

            /// <summary>
            /// The Homepage item.
            /// </summary>
            [RepositoryItem("e28361f0-555e-42ed-a7f5-2343884a426e")]
            public virtual Ranorex.ATag Homepage
            {
                get
                {
                    return _homepageInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Homepage item info.
            /// </summary>
            [RepositoryItemInfo("e28361f0-555e-42ed-a7f5-2343884a426e")]
            public virtual HomepageInfoClass HomepageInfo
            {
                get
                {
                    return _homepageInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}