///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RxDatabase
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The GmailLogin recording.
    /// </summary>
    [TestModule("44cc5d1d-7783-4790-9fc4-00e8bf58b187", ModuleType.Recording, 1)]
    public partial class GmailLogin : ITestModule
    {
        /// <summary>
        /// Holds an instance of the RxDatabaseRepository repository.
        /// </summary>
        public static RxDatabaseRepository repo = RxDatabaseRepository.Instance;

        static GmailLogin instance = new GmailLogin();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public GmailLogin()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static GmailLogin Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'http://www.gmail.com' with browser 'IE' in normal mode.", new RecordItemIndex(0));
            Host.Local.OpenBrowser("http://www.gmail.com", "IE", "", false, false, false, false, false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Explorer.MicrosoftEdge1RunningWindow' at 36;29.", repo.Explorer.MicrosoftEdge1RunningWindowInfo, new RecordItemIndex(1));
            repo.Explorer.MicrosoftEdge1RunningWindow.Click("36;29");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MicrosoftEdge.Minimize' at 17;11.", repo.MicrosoftEdge.MinimizeInfo, new RecordItemIndex(2));
            repo.MicrosoftEdge.Minimize.Click("17;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Gmail.IdentifierId' at 243;36.", repo.Gmail.IdentifierIdInfo, new RecordItemIndex(3));
            repo.Gmail.IdentifierId.Click("243;36");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'shakthy' with focus on 'Gmail.IdentifierId'.", repo.Gmail.IdentifierIdInfo, new RecordItemIndex(4));
            repo.Gmail.IdentifierId.PressKeys("shakthy");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GmailInternetExplorer.AskMeLater' at 94;11.", repo.GmailInternetExplorer.AskMeLaterInfo, new RecordItemIndex(5));
            repo.GmailInternetExplorer.AskMeLater.Click("94;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Value='shakthy') on item 'Gmail.IdentifierId'.", repo.Gmail.IdentifierIdInfo, new RecordItemIndex(6));
            Validate.Attribute(repo.Gmail.IdentifierIdInfo, "Value", "shakthy");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Gmail.ZFr60dCeoRYc'.", repo.Gmail.ZFr60dCeoRYcInfo, new RecordItemIndex(7));
            Validate.Exists(repo.Gmail.ZFr60dCeoRYcInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Gmail.Next' at 24;13.", repo.Gmail.NextInfo, new RecordItemIndex(8));
            repo.Gmail.Next.Click("24;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Gmail.Password'.", repo.Gmail.PasswordInfo, new RecordItemIndex(9));
            Validate.Exists(repo.Gmail.PasswordInfo);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
